In [7]:
import torch
import torch.nn as nn

# Przykładowe dane wejściowe - obraz o wymiarach 1x3x4x4 (batch_size x channels x height x width)
input_data = torch.tensor([[[[1.0, 2.0, 3.0, 4.0],
                              [5.0, 6.0, 7.0, 8.0],
                              [9.0, 10.0, 11.0, 12.0],
                              [13.0, 14.0, 15.0, 16.0]]]])

# Definicja warstwy MaxPool2d
maxpool_layer = nn.MaxPool2d(kernel_size=2, stride=2)

# Przejście przez warstwę MaxPool2d
output = maxpool_layer(input_data)

# Wyświetlenie danych wyjściowych
print("Dane wyjściowe po MaxPooling:")
print(output)
print(input_data)


Dane wyjściowe po MaxPooling:
tensor([[[[ 6.,  8.],
          [14., 16.]]]])
tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])


In [5]:
import torch
import torch.nn as nn

# Definiujemy klasę sieci
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)

# Tworzymy instancję klasy sieci
net = Net()

# Definiujemy przykładowe dane wejściowe (batch_size x channels x height x width)
input_data = torch.randn(1, 3, 32, 32)  # Przykładowe dane wejściowe o wymiarach 32x32

# Przechodzimy przez warstwę Conv2d
output = net.conv1(input_data)

# Wyświetlamy rozmiar danych wyjściowych
print("Rozmiar danych wyjściowych:", output.size())


Rozmiar danych wyjściowych: torch.Size([1, 6, 28, 28])


In [9]:
import torch
import torch.nn.functional as F

# Przykładowe dane wejściowe
input_data = torch.randn(3, 3)  # Rozmiar: batch_size x liczba cech

# Obliczenie funkcji aktywacji ReLU
output = F.relu(input_data)

# Wyświetlenie danych wyjściowych
print(input_data)
print("Dane wyjściowe po zastosowaniu ReLU:")
print(output)


tensor([[ 0.2548, -0.7505, -0.1318],
        [-0.5404,  0.6434,  1.2339],
        [-1.4786,  0.4105,  0.3073]])
Dane wyjściowe po zastosowaniu ReLU:
tensor([[0.2548, 0.0000, 0.0000],
        [0.0000, 0.6434, 1.2339],
        [0.0000, 0.4105, 0.3073]])


In [1]:
import numpy as np

np.convolve((1,2,3), (4,5,6))

array([ 4, 13, 28, 27, 18])